name: Scoop Install Tests

on:
  push:
    branches:
      - 'main'
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        shell: [
          "powershell",
          "cmd"
          ]
        os: [
          "windows-latest",
          "windows-11-arm"
          ]
        package: [
          "pact-legacy",
          "pact",
          "pact-plugin",
          "pact-verifier",
          "pact-stub-server",
          "pact-mock-server",
          "pact-broker-client"
          ]
    defaults:
      run:
        shell: ${{ matrix.shell }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Bucket
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a # main
      - name: install scoop
        shell: powershell
        if: runner.os == 'windows'
        run: |
          iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
          "$HOME\scoop\shims\" >> $env:GITHUB_PATH

      - name: Use external 7zip on ARM64 due to extract error
        if: ${{ matrix.os == 'windows-11-arm' && ( matrix.package == 'pact-verifier' || matrix.package == 'pact-plugin' || matrix.package == 'pact-mock-server' || matrix.package == 'pact-stub-server') }}
        shell: powershell
        run: |
          scoop config use_external_7zip true

      - name: Add Pact Scoop Bucket
        run: |
          scoop bucket add pact https://github.com/you54f/scoop

      - name: Install ${{ matrix.package }} Package
        run: |
          scoop install ${{ matrix.package }}

      - name: Test pact-legacy scripts
        if: matrix.package == 'pact-legacy'
        run: |
          pact-broker --help
          pact-message --help
          pact-mock-service --help
          pact-provider-verifier --help
          pact-stub-service --help
          pactflow --help

      - name: Test ${{ matrix.package }} scripts
        if: matrix.package != 'pact-legacy'
        run: |
          ${{ matrix.package }} --help
      - name: Uninstall ${{ matrix.package }} Package
        run: |
          scoop uninstall ${{ matrix.package }}
